includes:
  - python-file: openstack_functions.py

pipelines:
  - name: check
    manager: IndependentPipelineManager
    trigger:
      gerrit:
        - event: patchset-created
        - event: change-restored
        - event: comment-added
          comment_filter: (?i)^\s*recheck(( (?:bug|lp)[\s#:]*(\d+))|( no bug)|( savanna-ci))\s*$
        - event: comment-added
          require-approval:
            - username: savanna-ci
              older-than: 48h
    start:
      gerrit:
        verified: 0
    success:
      gerrit:
        verified: 1
    failure:
      gerrit:
        verified: -1

projects:
  - name: openstack/sahara
    check:
      - gate-sahara-integration-hdp
      - gate-sahara-integration-vanilla
      - gate-sahara-integration-idh
      - gate-sahara-integration-transient

  - name: openstack/sahara-dashboard
    check:
      - gate-ui-tests
      
  - name: openstack/sahara-image-elements
    check:
      - diskimage-integration-ubuntu   
      - diskimage-integration-fedora
      - diskimage-integration-centos

jobs:
  - name: ^.*$
    parameter-function: set_log_url
    branch: ^master$
  - name: gate-sahara-integration-transient
    voting: false
  - name: gate-sahara-integration-vanilla2
    voting: false
  - name: gate-ui-tests
    parameter-function: single_use_node
  - name: diskimage*$
    parameter-function: single_use_node
